### PR TITLE
Added APK REST API catalogs

### PR DESCRIPTION
**Pull request by Mariangela**
## Purpose
Add the all the APK REST API catalogs.

### Screenshots
Check the comments below for the respective screenshots.

### CODE REVIEW

**Comment by Mariangela** [comment]
### BackOffice API Catalog

Screenshot 2023-03-10 at 11 31 27 AM

Screenshot 2023-03-10 at 11 31 46 AM

**Comment by Mariangela** [comment]
### DevPortal API Catalog

Screenshot 2023-03-10 at 11 56 35 AM

Screenshot 2023-03-10 at 11 56 50 AM

**Comment by Mariangela** [comment]
### Runtime API Catalog
Screenshot 2023-03-10 at 11 56 13 AM
Screenshot 2023-03-10 at 11 56 25 AM

**Comment by Mariangela** [comment]
### Overview page

Screenshot 2023-03-10 at 12 09 45 PM

**Review by ruthryi — APPROVED** [review]

**Pull request merged**
