### PR TITLE
Updating theme

### PR DESCRIPTION
**Pull request by chanaka3d**
## Purpose
Updating theme.

https://github.com/wso2/docs-apk/issues/54

screencapture-localhost-8000-about-apk-what-is-apk-2023-03-08-21_00_53

screencapture-localhost-8000-2023-03-08-21_01_31

Screen Shot 2023-03-08 at 9 29 21 PM

### CODE REVIEW

**Review by sanjeewa-malalgoda — APPROVED** [review]

**Comment by Mariangela** [comment]
@chanaka3d , we need to add the following copyrights statement. Similar to APIM [1]

Copyright © [WSO2 LLC](https://wso2.com/) (2023)
Content licensed under [CC By 4.0.](https://creativecommons.org/licenses/by/4.0) | Sample code licensed under [Apache 2.0](http://www.apache.org/licenses/).

[1] https://apim.docs.wso2.com/en/latest/

**Review by Mariangela — APPROVED** [review]

**Comment by Mariangela** [comment]
It will be nice to have the home icon of the little house as well similar to [1]

[1] https://apim.docs.wso2.com/en/latest/

**Comment by Mariangela** [comment]
The Work in process icon is not properly visible on a lower resolution, as in when looking at this on a mobile phone.
WhatsApp Image 2023-03-09 at 9 22 41 AM (1)

WhatsApp Image 2023-03-09 at 9 22 41 AM

**Comment by Mariangela** [comment]
There is a mismatch in the size of the bullets and regular text used for it. At times the text of the bullet looks larger and the regular text that follows the font and wise versa.

Screenshot 2023-03-09 at 9 36 46 AM

**Comment by chanaka3d** [comment]
Footer issue and the mobile view are fixed with https://github.com/wso2/docs-apk/pull/63

**Pull request merged**
